### ISSUE TITLE
SQL Error: 'ER_BAD_FIELD_ERROR' when seeding

### ISSUE THREAD

**Issue by jenho-webdev** [jenho-webdev/TuneStack#3]
code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'title' in 'field list'",
    sql: "INSERT INTO `album` (`id`,`title`,`url`,`artist`,`year`,`genre`,`description`,`creator_id`,`created_at`,`updated_at`) VALUES (NULL,'Thriller','https://example.com/thriller','Michael Jackson','1982','Pop','Thriller is the sixth studio album by American singer Michael Jackson',1,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Abbey Road','https://example.com/abbey-road','The Beatles','1969','Rock','Abbey Road is the eleventh studio album by English rock band the Beatles',2,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'The Dark Side of the Moon','https://example.com/dark-side-of-the-moon','Pink Floyd','1973','Progressive Rock','The Dark Side of the Moon is the eighth studio album by English rock band Pink Floyd',1,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Back in Black','https://example.com/back-in-black','AC/DC','1980','Hard Rock','Back in Black is the seventh studio album by Australian rock band AC/DC',3,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Hotel California','https://example.com/hotel-california','Eagles','1976','Rock','Hotel California is the fifth studio album by American rock band Eagles',2,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Nevermind','https://example.com/nevermind','Nirvana','1991','Grunge','Nevermind is the second studio album by American rock band Nirvana',3,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'The Joshua Tree','https://example.com/joshua-tree','U2','1987','Rock','The Joshua Tree is the fifth studio album by Irish rock band U2',1,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Rumours','https://example.com/rumours','Fleetwood Mac','1977','Rock','Rumours is the eleventh studio album by British-American rock band Fleetwood Mac',2,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Born to Run','https://example.com/born-to-run','Bruce Springsteen','1975','Rock','Born to Run is the third studio album by American singer-songwriter Bruce Springsteen',3,'2023-07-12 05:29:47','2023-07-12 05:29:47'),(NULL,'Led Zeppelin IV','https://example.com/led-zeppelin-iv','Led Zeppelin','1971','Rock','Led Zeppelin IV is the fourth studio album by English rock band Led Zeppelin',1,'2023-07-12 05:29:47','2023-07-12 05:29:47');",

**Comment by jenho-webdev** [comment]
![image_720](https://github.com/jenho-webdev/TuneStack/assets/129031553/678971dd-6e12-4a7b-9d10-7ecb3ad091b2)

the tables/objects relationship that is defined now in the models/index.js is likely causing a marge issue. will have to spend some time to look into it and redefining them.

**Comment by jenho-webdev** [comment]
Creating a new board in Figma to build out the relationship databases

**Comment by saduhub** [comment]
Favorite model was accidentally set to be recognized as album. this resulted in album schema being synced and following the specification of favorite. This resulted in a field error when there was an attempt to seed.
